export const BONE = {
  hipH: 0.95,
  pelvis: { rx: 0.16, ry: 0.10, rz: 0.12 },
  torsoLen: 0.46, torsoR: 0.16,
  headR: 0.14,
  shoulderY: 0.40, shoulderX: 0.22,
  upperArmLen: 0.30, upperArmR: 0.07,
  forearmLen: 0.28, forearmR: 0.06,
  handR: 0.07,
  hipX: 0.13,
  thighLen: 0.44, thighR: 0.10,
  shinLen: 0.42, shinR: 0.08,
  foot: { rx: 0.07, ry: 0.04, rz: 0.13 }
};

export const CONFIG = {
  walkSpeed: 3.8,
  sprintMult: 1.65,
  aimMult: 0.5,
  gravity: -19.62,
  mouseBaseSens: 0.0022,
  camDistanceNormal: 3.5,
  camDistanceAim: 2.3,
  camHeight: 1.55,
  camSideOffset: 0.95,
  camSideOffsetAim: 0.80,
  fovNormal: 90,
  fovAimRatio: 0.99,
  fireCooldown: 0.1,
  magSize: 12,
  reloadTime: 1.1,
  ragdollMassMultiplier: 2.0,
  impactForceMultiplier: 0.50,
  cameraShake: 0.85,
  cameraSmoothing: 0.72,
  firstPerson: false,
  headBobEnabled: true,
  headBobStrength: 0.35,
  recoilEnabled: true,
  recoilStrength: 2,
  recoilRecovery: 2,
  bloodDecalLifetime: 7.0,
  autoReload: true,
  infiniteAmmo: false,
  unlimitedFireRate: false,
  oneHit: false,
  invertY: false,
  gravityStrength: 9.81,
  jointLooseness: 1.0,
  hitboxScale: 1.0,
  showHitboxes: false,
  ragdollAngularDamping: 0.20,
  ragdollLinearDamping: 0.16,
  ragdollJointLimits: true,
  ragdollLooseSettling: true,
  ragdollStability: true,
  stabilityStrength: 0.65,
  ragdollSettleTime: 0.55,
  groundDamping: 0.65,
  airborneAngularDamping: 0.10,
  secondaryMotion: true,
  physicsSubsteps: 12,
  painWrithingEnabled: true,
  painWrithingIntensity: 0.35,
  painRollAmount: 0.35,
  painWrithingDuration: 3.5,
  painLimpEnabled: true,
  limpRelaxSpeed: 0.95,
  impactSpin: 1,
  ragdollFriction: 0.8,
  painLegKickingEnabled: true,
  painLegKickIntensity: 0.55,
  painLegKickRate: 1.0,
  wincingChance: 0.65,
  stumbleChance: 0.4,
  stumbleDurationMin: 0.35,
  stumbleDurationMax: 0.85,
  stumbleStrength: 1.0,
  bloodParticleMultiplier: 6,
  bloodParticleLifetime: 1.0,
  bloodSplashEnabled: true,
  bloodLandingDotsEnabled: true,
  bloodDotSize: 2.5,
  bloodDotScatter: 0.65,
  bloodPoolsEnabled: true,
  bloodPoolDelay: 1.4,
  bloodPoolSpreadTime: 3.2,
  bloodPoolSize: 1.2,
  bloodPoolOpacity: 0.72,
  bloodDotLifetime: 12,

  damageMarksEnabled: true,
  damageMarkCap: 500,
  damageMarkSize: 0.05,
  bulletHolesEnabled: true,
  bulletHoleCap: 450,
  headshotDebrisEnabled: true,
  headshotDebrisPerHit: 10,
  goreDebrisCap: 280,
  dismembermentEnabled: true,
  dismemberHitThreshold: 3,
  jointStrength: 1.0,
  postDeathHits: true,
  showTips: false,
  showCrosshair: true,
  hideAllUi: false,
  timeScale: 1.0,
  ragdollResetTime: 25,
  ragdollNeverDespawn: false,
  weapon: 'pistol',
  arenaHalf: 60,
  buildingCount: 3,
  buildingRoomTarget: 7,
  buildingDummiesEnabled: true,
  buildingDummiesPerRoom: 0.4,
  buildingDummiesMax: 6,
  npcCount: 10,
  ragdollInheritVelocity: true,
  playerRadius: 0.42,
  npcRadius: 0.42,
  npcPathRecalc: 0.45,
  npcWalkSpeedMin: 1.40,
  npcWalkSpeedMax: 1.90,
  npcWanderMargin: 2.5,
  npcTurnRate: 4.5,
  npcDirectionVariance: 0.45,
  npcPauseMin: 0.7,
  npcPauseMax: 2.6,
  npcWanderMin: 3.5,
  npcWanderMax: 8.0,
  npcSeparation: 1.15,
  npcPanic: true,
  npcGroupPanic: true,
  npcPanicDuration: 5.5,
  npcPanicSpeedMin: 3.9,
  npcPanicSpeedMax: 4.8,
  fallSaveEnabled: true,
  fallSaveDuration: 1.35,
  fallSaveFadeStart: 0.30,
  fallSaveStrength: 1.0,
  ragdollCollisionSounds: true
};

export const SKIN_COLOR  = 0xd6a179;
export const SHIRT_COLOR = 0xb91c1c;
export const NPC_SHIRT_COLORS = [0xb91c1c, 0x2563eb, 0x15803d, 0xeab308, 0xf5f5f5, 0x171717, 0x9d00ff];
export const JEANS_COLOR = 0x3d4a5c;
export const SHOE_COLOR  = 0x1a1a1a;
export const BELT_COLOR  = 0x2b2320;

export const GROUP_GROUND = 1;
export const GROUP_RAGDOLL = 2;
export const GROUP_SHELL = 4;

export const MAX_BLOOD_PARTICLES = 2600;
export const MAX_BLOOD_DECALS = 180;
export const MAX_BLOOD_POOLS = 90;
export const MAX_BLOOD_LANDING_DOTS = 1800;
export const MAX_SHELL_CASINGS = 45;